[build]
  command = "npm run build"
  publish = "dist"
  framework = "astro"

[functions]
  node_bundler = "esbuild"
  included_files = ["convex/**"]

[dev]
  framework = "astro"
  command = "npm run dev"

